service: serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: "*"

# you can define service wide environment variables here
environment:
  testenv: testenv-value

functions:
  hello:
    handler: handler.hello
